version: '3.3'
services:
    duas:
      image: mqzaidi/duas.mobi
      build: .
      environment:
        - EMAILUSER='qasim@zaidi.me'
        - EMAILPASS=$${EMAILPASS}
        - NODE_ENV=production
      ports: 
        - 3786:3786
      volumes:
        - public:/usr/src/app/public
        - ./src/data:/usr/src/app/src/data
      restart: always

    nginx:
      image: nginx:1.15-alpine
      ports:
        - 80:80
        - 443:443
      volumes:
        - public:/var/www/
        - ./cfg/nginx:/etc/nginx/conf.d
        - ./cfg/certbot/conf:/etc/letsencrypt
        - ./cfg/certbot/www:/var/www/certbot

    certbot:
      image: certbot/certbot
      volumes:
       - ./cfg/certbot/conf:/etc/letsencrypt
       - ./cfg/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  public:
