version: '3.3'
services:
    duas:
      image: mqzaidi/duas.mobi
      build: .
      environment:
        - EMAILUSER='qasim@zaidi.me'
        - EMAILPASS=$${EMAILPASS}
        - NODE_ENV=production
        - PDFSERVER=pdfgen
      expose:
        - "3786"
      volumes:
        - public:/usr/src/app/public
        - ./src/data:/usr/src/app/src/data
      restart: always

#    nginx:
#      image: nginx:1.15-alpine
#      ports:
#        - 80:80
#        - 1443:443
#      volumes:
#        - public:/var/www/
#        - ./cfg/nginx:/etc/nginx/conf.d
#        - ./cfg/certbot/conf:/etc/letsencrypt
#        - ./cfg/certbot/www:/var/www/certbot
#
    front-envoy:
      image: envoyproxy/envoy-alpine
      volumes:
       - ./cfg/envoy/front-envoy.yaml:/etc/envoy/envoy.yaml
       - ./cfg/certbot/conf:/etc/letsencrypt
      ports:
       - 80:8001
       - 1443:1443

    certbot:
      image: certbot/certbot
      volumes:
       - ./cfg/certbot/conf:/etc/letsencrypt
       - ./cfg/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    pdfgen:
      image: restorecommerce/pdf-rendering-srv
      environment:
        - NODE_ENV=production
        - ALLOW_HTTP=true
      ports:
        - 9000:9000

volumes:
  public:
