version: '3.3'
services:
    duas:
      image: mqzaidi/duas.mobi
      build: .
      environment:
        - EMAILUSER='qasim@zaidi.me'
        - EMAILPASS=$${EMAILPASS}
        - NODE_ENV=production
      ports: 
        - 3786:3786

